### ISSUE TITLE
fabric8:deploy username and password tokens not replaced

### ISSUE THREAD

**Issue by gnunn1** [weimeilin79/financepipeline#5]
When you run the fabric8:deploy goal for fisdemoaccount, it doesn't replace the ${mysql-service-username} and ${mysql-service-password} tokens in /fisaccount-service/src/main/fabric8/deployment.yml. Instead you have to manually edit the deployment yaml in openshift. I assume these are supposed to be sourced from somewhere?

**Comment by gnunn1** [comment]
So this is how I fixed it, not sure it is the best way. First there is a typo in ```fisdemoaccount/src/main/fabric8/deployment.yml```. The ```mysql-service-username``` and ```mysql-service-password``` need to have the dashes changed to dot.

Second when running the fabric8:deploy goal, add properties for username and password:

```
mvn fabric8:deploy -Dmysql.service.username=dbuser -Dmysql.service.password=password
```

**Comment by weimeilin79** [comment]
Simple add the -Dmysql.service.username=dbuser -Dmysql.service.password=password will do the trick. I forgot to added to my instruction, thanks for the reminder!! Thank you !!
