### ISSUE TITLE
fisdemoaggregator transfer API doesn't work

### ISSUE THREAD

**Issue by gnunn1** [weimeilin79/financepipeline#7]
The transfer API in aggregator doesn't work as it seems to be using incorrect URLs and HTTP methods compared to what fisaccount and fisblockchain expose. I took a shot at fixing it (see PR) for fisaccount but it's still not working right and I ran out of time.

**Comment by weimeilin79** [comment]
Thanks for raising this issue. The problem was because is you use fabric8:deploy then it will automatic deploy the service as port 80, but with my Source2image template it export as 8080.
